"""Stage 6b: six gates and the budget sweep. Reads only results/tiers/predictions/ and configs.
Gates use on-device inputs only, are fitted and thresholded on gate_fit, evaluated on validation.
Writes configs/gate_thresholds.yaml and results/gates/."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import yaml

from escal import gates as G
from escal.bootstrap import avg_rmse, day_index, day_sums, interval, paired_diff, weights
from escal.data import load_config
from escal.models import EdgeNet
from escal.train import fit, predict, set_seed

PRED = Path("results/tiers/predictions")
OUT = Path("results/gates")
GATES = ["random", "fixed_interval", "variability", "uncertainty", "learned", "oracle"]


def load():
    truth = pd.read_parquet(PRED / "truth.parquet")
    inp = pd.read_parquet(PRED / "on_device_inputs.parquet")
    assert truth["timestamp"].equals(inp["timestamp"])
    tiers = {k: pd.read_parquet(PRED / f"{k}.parquet") for k in ("edge", "cloud", "trees_ground")}
    return truth, inp, tiers


def kt_array(df: pd.DataFrame, seed, hz) -> np.ndarray:
    d = df[df["seed"].astype(str) == str(seed)]
    return d[[f"kt_{h}" for h in hz]].values


CKPT = Path("checkpoints/gates")


def gate_net(X, target, tr, es, cfg, seed, name: str) -> np.ndarray:
    set_seed(seed)
    m = EdgeNet(X.shape[1], 1, cfg["gates"]["net_hidden"])
    data = {"x": X.astype(np.float32), "kt": target[:, None].astype(np.float32),
            "mask": np.ones((len(X), 1), np.float32), "tiles": None}
    fit(m, data, tr, es, cfg, seed, Path("logs/gates") / f"{name}_seed{seed}.json")
    (CKPT / f"seed{seed}").mkdir(parents=True, exist_ok=True)
    torch.save(m.state_dict(), CKPT / f"seed{seed}" / f"{name}.pt")
    return predict(m, data)[:, 0]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default="configs/base.yaml")
    cfg = load_config(ap.parse_args().config)
    gc, budgets, seeds = cfg["gates"], cfg["budget"]["targets"], cfg["seeds"]
    OUT.mkdir(parents=True, exist_ok=True)
    truth, inp, tiers = load()
    hz = [c[4:] for c in truth.columns if c.startswith("ghi_")]
    y = truth[[f"ghi_{h}" for h in hz]].values
    clear = truth[[f"clear_{h}" for h in hz]].values
    sp = truth[[f"sp_{h}" for h in hz]].values
    day = truth[[f"day_{h}" for h in hz]].values.astype(bool)
    pop = truth["sat_available"].values & day.any(1)
    gf = (truth["part"] == "gate_fit").values & pop
    va = (truth["part"] == "val").values & pop
    sel = day & pop[:, None]
    kt = truth[[f"kt_{h}" for h in hz]].values
    prev = np.column_stack([truth["B(ghi_kt|30min)"].values, kt[:, :-1]])
    ramp = sel & (np.abs(kt - prev) >= cfg["ramp"]["delta_kt"])
    ts = truth["timestamp"]
    dayid = day_index(ts)

    # gate_fit early-stop slice for the gate networks: its last es_days
    gf_end = ts[gf].max()
    es = gf & (ts >= gf_end.normalize() - pd.Timedelta(days=gc["es_days"] - 1)).values
    tr = gf & ~es

    trees = tiers["trees_ground"][[f"kt_{h}" for h in hz]].values * clear
    v = np.nonzero(va)[0]
    yv, spv, selv, rampv, dv = y[v], sp[v], sel[v], ramp[v], dayid[v]
    w_boot = weights(dv.max() + 1, cfg)
    rng = np.random.default_rng(0)
    thresholds, recs, boots, edge_cloud = {}, [], [], []

    scores_by_seed = {}
    for s in seeds:
        E = kt_array(tiers["edge"], s, hz) * clear
        C = kt_array(tiers["cloud"], s, hz) * clear
        cols = G.gate_input_columns(list(inp.columns[1:]) + [f"edge_kt_{h}" for h in hz], gc["forbidden_input_substrings"])
        X = pd.concat([inp.iloc[:, 1:], pd.DataFrame(kt_array(tiers["edge"], s, hz), columns=cols[-len(hz):])], axis=1)
        mu, sd = X[tr].mean(), X[tr].std().replace(0, 1).fillna(1)
        Xs = ((X - mu) / sd).fillna(0).values
        (CKPT / f"seed{s}").mkdir(parents=True, exist_ok=True)
        np.savez(CKPT / f"seed{s}" / "norm.npz", mu=mu.values, sd=sd.values, columns=np.array(cols))

        unc_t = np.where(sel, np.abs(y - E), np.nan)
        unc_t = np.nan_to_num(np.nanmean(unc_t, axis=1)) / gc["uncertainty_scale"]
        ben_c = G.benefit(y, E, C, sel)
        scores = {"variability": inp[gc["variability_feature"]].fillna(0).values,
                  "uncertainty": gate_net(Xs, unc_t, tr, es, cfg, s, "uncertainty"),
                  "learned": gate_net(Xs, ben_c / gc["benefit_scale"], tr, es, cfg, s, "learned")}
        thresholds[s] = {g: G.fit_thresholds(sc[gf], budgets) for g, sc in scores.items()}   # gate_fit only
        scores_by_seed[s] = scores

    # thresholds go to the config file first; evaluation reads them back from there
    Path(gc["thresholds_file"]).write_text(
        "# Generated by scripts/gates.py from gate_fit scores only. Do not edit by hand.\n"
        + yaml.safe_dump({"gate_thresholds": {int(s): {g: {float(b): float(t) for b, t in d.items()}
                                                       for g, d in gd.items()} for s, gd in thresholds.items()}}))
    tau = yaml.safe_load(Path(gc["thresholds_file"]).read_text())["gate_thresholds"]

    for s in seeds:
        E = kt_array(tiers["edge"], s, hz) * clear
        C = kt_array(tiers["cloud"], s, hz) * clear
        scores = scores_by_seed[s]
        Ev, Cv, Tv = E[v], C[v], trees[v]
        full = {"edge": G.avg_metrics(yv, Ev, spv, selv), "cloud": G.avg_metrics(yv, Cv, spv, selv),
                "trees_ground": G.avg_metrics(yv, Tv, spv, selv)}
        full_r = {k: G.avg_metrics(yv, p, spv, rampv) for k, p in (("edge", Ev), ("cloud", Cv), ("trees_ground", Tv))}
        edge_cloud.append({"seed": s, "edge_minus_cloud": paired_diff(yv, Ev, Cv, selv, ts.iloc[v], cfg),
                           "edge_minus_trees_ground": paired_diff(yv, Ev, Tv, selv, ts.iloc[v], cfg),
                           "rmse": {k: m["RMSE"] for k, m in full.items()}})
        sums = {k: day_sums(yv, p, selv, dv, dv.max() + 1) for k, p in (("edge", Ev), ("cloud", Cv))}
        re_b, rc_b = avg_rmse(*sums["edge"], w_boot), avg_rmse(*sums["cloud"], w_boot)

        for b in budgets:
            for target_name, Tg in (("cloud", Cv), ("trees_ground", Tv)):
                ben_t = G.benefit(yv, Ev, Tg, selv)
                for g in GATES:
                    if g == "random":
                        ms, mr = [], []
                        for _ in range(gc["n_random_draws"]):
                            esc = G.random_draw(len(v), b, rng)
                            P = G.blend(Ev, Tg, esc)
                            ms.append(G.avg_metrics(yv, P, spv, selv))
                            mr.append(G.avg_metrics(yv, P, spv, rampv))
                        m = {k: float(np.mean([x[k] for x in ms])) for k in ("RMSE", "MAE", "skill")}
                        m["rmse_per_horizon"] = np.mean([x["rmse_per_horizon"] for x in ms], 0).tolist()
                        mram = {k: float(np.mean([x[k] for x in mr])) for k in ("RMSE", "MAE", "skill")}
                        mram["rmse_per_horizon"] = np.mean([x["rmse_per_horizon"] for x in mr], 0).tolist()
                        rate = b
                        esc = None
                    else:
                        if g == "fixed_interval":
                            esc = G.fixed_interval(dv, b)
                        elif g == "oracle":
                            esc = G.oracle(ben_t, b)
                        else:
                            esc = G.decide(scores[g][v], tau[int(s)][g][float(b)])
                        P = G.blend(Ev, Tg, esc)
                        m, mram, rate = G.avg_metrics(yv, P, spv, selv), G.avg_metrics(yv, P, spv, rampv), float(esc.mean())
                    for rs, mm, fe, fc in (("primary", m, full["edge"], full["cloud"]),
                                           ("ramp", mram, full_r["edge"], full_r["cloud"])):
                        recs.append({"escalate_to": target_name, "gate": g, "budget_target": b, "seed": s,
                                     "row_set": rs, "realised_rate": rate, "n_issue_times": len(v),
                                     "RMSE": mm["RMSE"], "MAE": mm["MAE"], "skill": mm["skill"],
                                     "share_retained": G.share_retained(fe["RMSE"], mm["RMSE"], fc["RMSE"]),
                                     **{f"rmse_{h}": x for h, x in zip(hz, mm["rmse_per_horizon"])}})
                    if b in cfg["budget"]["report_at"]:
                        if esc is None:   # random: expected squared error per day
                            st = day_sums(yv, Tg, selv, dv, dv.max() + 1)
                            sg = (b * st[0] + (1 - b) * sums["edge"][0], sums["edge"][1])
                        else:
                            sg = day_sums(yv, G.blend(Ev, Tg, esc), selv, dv, dv.max() + 1)
                        rg_b = avg_rmse(*sg, w_boot)
                        rg = avg_rmse(*sg)
                        boots.append({"escalate_to": target_name, "gate": g, "budget_target": b, "seed": s,
                                      "rmse": interval(rg, rg_b, cfg),
                                      "share_retained": interval(G.share_retained(full["edge"]["RMSE"], rg, full["cloud"]["RMSE"]),
                                                                 (re_b - rg_b) / (re_b - rc_b), cfg)})
        print(f"seed {s} done", flush=True)

    sweep = pd.DataFrame(recs)
    sweep.to_csv(OUT / "sweep_validation.csv", index=False, float_format="%.4f")
    summ = (sweep.groupby(["escalate_to", "row_set", "gate", "budget_target"])
            .agg(realised_rate_mean=("realised_rate", "mean"), realised_rate_min=("realised_rate", "min"),
                 realised_rate_max=("realised_rate", "max"),
                 RMSE_mean=("RMSE", "mean"), RMSE_median=("RMSE", "median"), RMSE_min=("RMSE", "min"),
                 RMSE_max=("RMSE", "max"), share_mean=("share_retained", "mean"),
                 share_median=("share_retained", "median"), share_min=("share_retained", "min"),
                 share_max=("share_retained", "max"), skill_mean=("skill", "mean")).reset_index())
    summ.to_csv(OUT / "summary_validation.csv", index=False, float_format="%.4f")
    rows = []
    for r in boots:
        for k in ("rmse", "share_retained"):
            rows.append({**{x: r[x] for x in ("escalate_to", "gate", "budget_target", "seed")}, "metric": k, **r[k]})
    pd.DataFrame(rows).to_csv(OUT / "bootstrap_validation.csv", index=False, float_format="%.4f")
    (OUT / "edge_vs_cloud_bootstrap.json").write_text(json.dumps(edge_cloud, indent=2))
    meta = {"population": "validation issue times with a satellite frame (15-min rule) and >= 1 daylight horizon",
            "issue_times_validation": int(va.sum()), "issue_times_gate_fit": int(gf.sum()),
            "gate_net_train_rows": int(tr.sum()), "gate_net_es_rows": int(es.sum()),
            "ramp_cells_validation": int(ramp[v].sum()), "daylight_cells_validation": int(selv.sum()),
            "gate_input_columns": cols}
    (OUT / "meta.json").write_text(json.dumps(meta, indent=2))
    print(json.dumps({k: v for k, v in meta.items() if k != "gate_input_columns"}))


if __name__ == "__main__":
    main()
